### ISSUE TITLE
게시판 요구사항#1

### ISSUE THREAD

**Issue by 42jeelee** [42jeelee/demoBoard-server#1]
# 해야할 일
----
## 2024-10-08
- [x] #2
  + Post 엔티티 컬럼 추가.

## 2024-10-09
- [x] 카테고리 엔티티 만들기 #4
  + Post 엔티티 컬럼 추가. 
  + 1 Depth
    + id
    + name

- [x] 댓글 엔티티 만들기 #4
  > 부모 글이 삭제 -> 같이 지워짐
  + id
  + pId
  + author
  + content

## 2024-10-13
> 카테고리 주제 - 동물, 식물, 가족, 기타
- [x] 카테고리 조회 #6
- [x] 댓글 전체 조회(게시글에 관한) #6
- [x] 댓글 삭제 ( id ) #6

## 2024-10-16
> UI
- [ ] 목록
- [ ] 게시글 작성
- [ ] 게시글 수정
- [ ] 게시글 상세보기

## 2024-10-19
> QA
- [ ] 코드 정리

**Comment by rarelhw** [comment]
코드리뷰 볼게 없디.. ㅜㅜ 나 심심해..
